# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b5e5244c6cd737060135f37a510e937537641e1de6bcea2152dd67c2de208ec4fa0dd79091173a2bb0e218a7351c990a96221a34c6bb81638084a45799eb09e0

test:
  secret_key_base: 73f2ef6a2ccab0e628bebdab9a927295d4ae91c560490153b45f259f7eb5229295ccde0067c7dd8e59804463c59851a9e31415a27cf9df20d811111de6aeb350

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
